<?php

namespace MailBundle\Repository;

/**
 * LetterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LetterRepository extends \Doctrine\ORM\EntityRepository
{
}
